I18 angebot/anfragen card
KMS-WS20-T01/MyCargonaut pull request #39
Opened 2021-01-01 15:30 UTC by davidmrt98

Die Komponente nimmt nicht einfach ein Objekt vom Typ "Offer" (wie im Backend definiert) an, weil sich die Struktur der Daten nicht dafür eignet (z.B. muss die Komponente die durchschnittlichen Bewertungen der User darstellen, diese Info ist aber nicht im "Offer"-Interface enthalten und muss deshalb anderwärtig übermittelt werden). Habe deswegen einfach neue Typen für die Props definiert.

Die Komponente stellt jenachdem wie die Props genau aussehen (ist das Angebot ausstehend? gehört das Angebot zum eingeloggten User? usw.) die Card sehr unterschiedlich dar, deswegen ist die Datei mal wieder etwas länger ausgefallen. Ich sehe aber nicht wirklich eine sinnvolle Möglichkeit, das ganze in weitere Unterkomponenten aufzuteilen.

Insgesamt bin ich nicht komplett zufrieden hiermit, aber will nicht wirklich mehr Zeit darein investieren, weil wir ja auch vorankommen müssen :smile:

2021-01-01 15:34 UTC, davidmrt98 commented
Mir ist eben noch aufgefallen, dass das Tracking-Modal auch noch zum Issue gehört.

2021-01-02 08:54 UTC, mxsph requested changes
Sieht soweit gut aus :+1: 

Anmerkungen:

- Ich würde die Typen Definitionen (also z.B.: `TrackingDetails`, `OfferDetails` usw.) in eigene Dateien in einem Ordner namens ` model` packen
- Die Dateien `GridElement` und `UserSumary` würde ich noch in den Util Ordner verschieben (welcher eigetlich auch unter `components` sein sollte :smile:)
- Style:
  - Ich finde die Überschrift (als z.B.: `Datum`) ist noch etwas zu weit von dem Text (z.B.:  `2.1.2021` entfernt (bzw. die lücke ist etwas zu groß).
  - sollte laut mockup das ganze nicht noch runde ecken und einen Grauen rahmen haben? (oder willst du das in einem Übergeordneten Componenten machen?)
  - Wenn das Element (`Offer`) aufgeklapt ist würde ich noch einen `divider` hinzufügen. 

> ... deswegen ist die Datei mal wieder etwas länger ausgefallen. Ich sehe aber nicht wirklich eine sinnvolle Möglichkeit, das ganze in weitere Unterkomponenten aufzuteilen.

Ja auf den ersten blick fällt mir auch nichts sinnvolles ein, zunot können wir das später ja noch anpassen.

2021-01-02 08:54 UTC, mxsph commented on frontend/src/components/Offer/index.tsx
> +  // TODO: field for profile picture
Vtl. benötigt man hier gar kein Feld für das Profile Bild, da wir dies einfach mit einer einheitlichen url lösen können. Somit kann man sich diese url einfach mit der `id` zusammenbauen (also z.B. `/api/v1/user/:id/avatar/

2021-01-02 09:13 UTC, TimonPllkrn commented
Ich passe selber grade noch paar sachen an, kann also auch den pull request bearbeiten :+1:

2021-01-02 13:01 UTC, TimonPllkrn commented
**Changes:**

- borderRadius von TrackingDialog und Card angepasst
- CargoCoinsIcon hinzugefügt
- Dropdown für Avatar hinzugefügt, wenn ein Angebot/Anfrage angenommen
- Abstände angepasst
- Schatten der Card angepasst
- Divider hinzugefügt
- Struktur angepasst

2021-01-02 15:36 UTC, davidmrt98 commented
Sollte jetzt gemerget werden können oder?

2021-01-02 15:53 UTC, mxsph approved these changes

2021-01-02 15:53 UTC, merged